In [1]:
import numpy as np

In [2]:
 # Creating a 1D array using a list
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array: \n", array_1d)

1D Array: 
 [1 2 3 4 5]


In [3]:
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", array_2d)


2D Array:
 [[1 2 3]
 [4 5 6]]


In [4]:
# Array characteristics
print("\nArray Shape:", array_2d.shape)
print("Array Data Type:", array_2d.dtype)
print("Array Size:", array_2d.size)


Array Shape: (2, 3)
Array Data Type: int32
Array Size: 6


In [9]:
# Basic operations on arrays
array_sum = np.sum(array_1d)
print("\nSum of 1D Array elements:", array_sum)
array_mean = np.mean(array_2d)
print("Mean of 2D Array elements:", array_mean)


Sum of 1D Array elements: 15
Mean of 2D Array elements: 3.5


In [10]:
 # Array creation using arange and reshape
array_arange = np.arange(10)
array_reshaped = array_arange.reshape(2, 5)
print("\nArray created using arange and reshaped: \n", array_reshaped)


Array created using arange and reshaped: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
# Creating arrays of zeros and ones
array_zeros = np.zeros((3, 3))
print("\nArray of zeros: \n", array_zeros)
array_ones = np.ones((2, 4))
print("\nArray of ones: \n", array_ones)


Array of zeros: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array of ones: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
# Creating an identity matrix
identity_matrix = np.eye (4)
print("\nIdentity matrix:\n", identity_matrix)


Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
# Element-wise operations
array_squared = array_1d ** 2
print("\nElement-wise square of 1D Array: \n", array_squared)
array_sum_2d = np.sum(array_2d, axis=0) # Sum along columns
print("\nSum of 2D Array elements along columns: \n", array_sum_2d)
array_sum_2d_row= np. sum (array_2d, axis=1)
np.sum(array_2d, axis=1) # Sum along rows
print("Sum of 2D Array elements along rows: \n", array_sum_2d_row)


Element-wise square of 1D Array: 
 [ 1  4  9 16 25]

Sum of 2D Array elements along columns: 
 [5 7 9]
Sum of 2D Array elements along rows: 
 [ 6 15]


In [19]:
# Array indexing and slicing
print("\nElement at index 1 in 1D Array:", array_1d[1])
print("Element at position (0, 2) in 2D Array: ", array_2d [0, 2])
array_slice_1d = array_1d[1:4]
print("\nSliced 1D Array (index 1 to 3): \n", array_slice_1d)
array_slice_2d = array_2d[:, 1:3] # Slicing columns 1 to 2
print("Sliced 2D Array (columns 1 to 2):\n", array_slice_2d)


Element at index 1 in 1D Array: 2
Element at position (0, 2) in 2D Array:  3

Sliced 1D Array (index 1 to 3): 
 [2 3 4]
Sliced 2D Array (columns 1 to 2):
 [[2 3]
 [5 6]]


In [21]:
# Boolean indexing
array_bool = array_1d [array_1d > 3]
print("\nElements greater than 3 in 1D Array: \n", array_bool)


Elements greater than 3 in 1D Array: 
 [4 5]


In [23]:
# Operations on reshaped arrays
array_reshaped_T = array_reshaped. T # Transpose of reshaped array
print("\nTranspose of the reshaped array:\n", array_reshaped_T)


Transpose of the reshaped array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [25]:
# Flattening the array
array_flattened = array_2d.flatten()
print("\nFlattened 2D Array: \n", array_flattened)


Flattened 2D Array: 
 [1 2 3 4 5 6]


In [27]:
 # Concatenating arrays
array_concat = np.concatenate((array_1d, array_1d), axis=0)
print("\nConcatenated 1D Arrays along axis 0:\n", array_concat)


Concatenated 1D Arrays along axis 0:
 [1 2 3 4 5 1 2 3 4 5]


In [29]:
 # Sorting an array
sorted_array = np.sort(array_1d)
print("\nSorted 1D Array:\n", sorted_array)


Sorted 1D Array:
 [1 2 3 4 5]


In [31]:
 # Finding unique elements
unique_elements = np. unique (array_2d)
print("\nUnique elements in 2D Array: \n", unique_elements)


Unique elements in 2D Array: 
 [1 2 3 4 5 6]


In [33]:
 # Finding maximum and minimum
max_value = np.max(array_2d)
min_value = np.min(array_2d)
print("\nMaximum value in 2D Array:", max_value)
print("Minimum value in 2D Array:", min_value)


Maximum value in 2D Array: 6
Minimum value in 2D Array: 1
